/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    '../../packages/uikit/src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: ['class', '[data-mode="dark"]'],

  theme: {
    screens: {
      xs: '576px',
      sm: '768px',
      md: '992px',
      lg: '1200px',
      xl: '1440px',
    },
    extend: {
      gridTemplateColumns: {
        14: 'repeat(14, minmax(0, 1fr))',
        16: 'repeat(16, minmax(0, 1fr))',
        24: 'repeat(24, minmax(0, 1fr))',
      },
      colors: {
        line: {
          0: 'rgb(var(--color-line-0) / <alpha-value>)',
          1: 'rgb(var(--color-line-1) / <alpha-value>)',
          2: 'rgb(var(--color-line-2) / <alpha-value>)',
          3: 'rgb(var(--color-line-3) / <alpha-value>)',
        },
        bg: {
          0: 'rgb(var(--color-bg-0) / <alpha-value>)',
          1: 'rgb(var(--color-bg-1) / <alpha-value>)',
          2: 'rgb(var(--color-bg-2) / <alpha-value>)',
          3: 'rgb(var(--color-bg-3) / <alpha-value>)',
        },
        text: {
          0: 'rgb(var(--color-text-0) / <alpha-value>)',
          1: 'rgb(var(--color-text-1) / <alpha-value>)',
          2: 'rgb(var(--color-text-2) / <alpha-value>)',
          3: 'rgb(var(--color-text-3) / <alpha-value>)',
          4: 'rgb(var(--color-text-4) / <alpha-value>)',
        },
        grey: {
          0: 'rgb(var(--color-grey-0) / <alpha-value>)',
          1: 'rgb(var(--color-grey-1) / <alpha-value>)',
          2: 'rgb(var(--color-grey-2) / <alpha-value>)',
          3: 'rgb(var(--color-grey-3) / <alpha-value>)',
          4: 'rgb(var(--color-grey-4) / <alpha-value>)',
          5: 'rgb(var(--color-grey-5) / <alpha-value>)',
          6: 'rgb(var(--color-grey-6) / <alpha-value>)',
          7: 'rgb(var(--color-grey-7) / <alpha-value>)',
          8: 'rgb(var(--color-grey-8) / <alpha-value>)',
          9: 'rgb(var(--color-grey-9) / <alpha-value>)',
        },
        purple: {
          0: 'rgb(var(--color-purple-0) / <alpha-value>)',
          1: 'rgb(var(--color-purple-1) / <alpha-value>)',
          2: 'rgb(var(--color-purple-2) / <alpha-value>)',
          3: 'rgb(var(--color-purple-3) / <alpha-value>)',
          4: 'rgb(var(--color-purple-4) / <alpha-value>)',
          5: 'rgb(var(--color-purple-5) / <alpha-value>)',
          6: 'rgb(var(--color-purple-6) / <alpha-value>)',
          7: 'rgb(var(--color-purple-7) / <alpha-value>)',
          8: 'rgb(var(--color-purple-8) / <alpha-value>)',
          9: 'rgb(var(--color-purple-9) / <alpha-value>)',
        },
        white: {
          0: 'var(--color-white-0)',
          1: 'var(--color-white-1)',
          2: 'var(--color-white-2)',
          3: 'var(--color-white-3)',
          4: 'var(--color-white-4)',
          5: 'var(--color-white-5)',
          6: 'var(--color-white-6)',
          7: 'var(--color-white-7)',
          8: 'var(--color-white-8)',
          9: 'rgb(var(--color-white-9) / <alpha-value>)',
        },
        green: {
          0: 'rgb(var(--color-green-0) / <alpha-value>)',
          1: 'rgb(var(--color-green-1) / <alpha-value>)',
          2: 'rgb(var(--color-green-2) / <alpha-value>)',
          3: 'rgb(var(--color-green-3) / <alpha-value>)',
          4: 'rgb(var(--color-green-4) / <alpha-value>)',
          5: 'rgb(var(--color-green-5) / <alpha-value>)',
          6: 'rgb(var(--color-green-6) / <alpha-value>)',
          7: 'rgb(var(--color-green-7) / <alpha-value>)',
          8: 'rgb(var(--color-green-8) / <alpha-value>)',
          9: 'rgb(var(--color-green-9) / <alpha-value>)',
        },
        red: {
          0: 'rgb(var(--color-red-0) / <alpha-value>)',
          1: 'rgb(var(--color-red-1) / <alpha-value>)',
          2: 'rgb(var(--color-red-2) / <alpha-value>)',
          3: 'rgb(var(--color-red-3) / <alpha-value>)',
          4: 'rgb(var(--color-red-4) / <alpha-value>)',
          5: 'rgb(var(--color-red-5) / <alpha-value>)',
          6: 'rgb(var(--color-red-6) / <alpha-value>)',
          7: 'rgb(var(--color-red-7) / <alpha-value>)',
          8: 'rgb(var(--color-red-8) / <alpha-value>)',
          9: 'rgb(var(--color-red-9) / <alpha-value>)',
        },
        blue: {
          0: 'rgb(var(--color-blue-0) / <alpha-value>)',
          1: 'rgb(var(--color-blue-1) / <alpha-value>)',
          2: 'rgb(var(--color-blue-2) / <alpha-value>)',
          3: 'rgb(var(--color-blue-3) / <alpha-value>)',
          4: 'rgb(var(--color-blue-4) / <alpha-value>)',
          5: 'rgb(var(--color-blue-5) / <alpha-value>)',
          6: 'rgb(var(--color-blue-6) / <alpha-value>)',
          7: 'rgb(var(--color-blue-7) / <alpha-value>)',
          8: 'rgb(var(--color-blue-8) / <alpha-value>)',
          9: 'rgb(var(--color-blue-9) / <alpha-value>)',
        },
        yellow: {
          0: 'rgb(var(--color-yellow-0) / <alpha-value>)',
          1: 'rgb(var(--color-yellow-1) / <alpha-value>)',
          2: 'rgb(var(--color-yellow-2) / <alpha-value>)',
          3: 'rgb(var(--color-yellow-3) / <alpha-value>)',
          4: 'rgb(var(--color-yellow-4) / <alpha-value>)',
          5: 'rgb(var(--color-yellow-5) / <alpha-value>)',
          6: 'rgb(var(--color-yellow-6) / <alpha-value>)',
          7: 'rgb(var(--color-yellow-7) / <alpha-value>)',
          8: 'rgb(var(--color-yellow-8) / <alpha-value>)',
          9: 'rgb(var(--color-yellow-9) / <alpha-value>)',
        },
        orange: {
          0: 'rgb(var(--color-orange-0) / <alpha-value>)',
          1: 'rgb(var(--color-orange-1) / <alpha-value>)',
          2: 'rgb(var(--color-orange-2) / <alpha-value>)',
          3: 'rgb(var(--color-orange-3) / <alpha-value>)',
          4: 'rgb(var(--color-orange-4) / <alpha-value>)',
          5: 'rgb(var(--color-orange-5) / <alpha-value>)',
          6: 'rgb(var(--color-orange-6) / <alpha-value>)',
          7: 'rgb(var(--color-orange-7) / <alpha-value>)',
          8: 'rgb(var(--color-orange-8) / <alpha-value>)',
          9: 'rgb(var(--color-orange-9) / <alpha-value>)',
        },
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
  plugins: [require('tailwindcss-safe-area')],
};
