export const FiatSymbols = {
  usd: '$',
};

export const CoingeckoFiatIdMap = {
  btc: 'bitcoin',
  usdt: 'tether',
  eth: 'ethereum',
  weth: 'ethereum',
  usdc: 'usd-coin',
  bnb: 'binancecoin',
  busd: 'binance-usd',
  xrp: 'ripple',
  ada: 'cardano',
  sol: 'solana',
  doge: 'dogecoin',
  dot: 'polkadot',
  dai: 'dai',
  shib: 'shiba-inu',
  trx: 'tron',
  leo: 'leo-token',
  avax: 'avalanche-2',
  wbtc: 'wrapped-bitcoin',
  matic: 'matic-network',
  steth: 'staked-ether',
  ltc: 'litecoin',
  ftt: 'ftx-token',
  okb: 'okb',
  link: 'chainlink',
  cro: 'crypto-com-chain',
  xlm: 'stellar',
  uni: 'uniswap',
  atom: 'cosmos',
  near: 'near',
  xmr: 'monero',
  xcn: 'chain-2',
  algo: 'algorand',
  etc: 'ethereum-classic',
  bch: 'bitcoin-cash',
  tfuel: 'theta-fuel',
  vet: 'vechain',
  icp: 'internet-computer',
  flow: 'flow',
  mana: 'decentraland',
  xtz: 'tezos',
  sand: 'the-sandbox',
  frax: 'frax',
  hbar: 'hedera-hashgraph',
  ape: 'apecoin',
  tusd: 'true-usd',
  fil: 'filecoin',
  egld: 'elrond-erd-2',
  theta: 'theta-token',
  axs: 'axie-infinity',
  hnt: 'helium',
  qnt: 'quant-network',
};

export const BNSymbols = {
  ethereum: 'ETHUSDT',
};
